doc(UIKIT-772,MobxQuery): Документация
kaluga-astral/mobx-query pull request #11
Opened 2023-07-05 07:58 UTC by Ofigelov

# Чеклист

- [ ] Написать тесты
- [ ] Описать jsdoc
- [ ] Обновить документацию в README.md

2023-07-05 10:40 UTC, AndTem requested changes

2023-07-05 10:40 UTC, AndTem commented on README.md
> +[Пример в sandbox](https://codesandbox.io/s/adoring-wing-z8s9ng)
Сюда надо добавить отображение isLoading

2023-07-05 10:40 UTC, AndTem commented on README.md
> +[Пример в sandbox](https://codesandbox.io/s/adoring-wing-z8s9ng)
Все эти примеры в md лучше выделить заголовком или хотя бы жирным

2023-07-05 10:40 UTC, AndTem commented on README.md
> +
Не хватает table of contents

2023-07-05 10:40 UTC, AndTem commented on README.md
> +# @astral/mobx-query
В доке не хватает инфы о флагал и полях, которые предоставляют query

2023-07-05 10:43 UTC, AndTem commented on README.md
> +### async вариация
```suggestion
## async вариация
```

2023-07-06 10:50 UTC, AndTem approved these changes

2023-07-07 06:59 UTC, StanislavDa approved these changes

2023-07-07 07:46 UTC, merged