feat(UIKIT-917,MobxQuery): Добавлен функционал массовой инвалидации
kaluga-astral/mobx-query pull request #14
Opened 2023-09-14 10:14 UTC by Ofigelov

# Чеклист

- [х] Написать тесты
- [х] Описать jsdoc
- [х] Обновить документацию в README.md

2023-09-14 10:20 UTC, sk-iv commented on package/src/MobxQuery/MobxQuery.test.ts
> +  it('invalidateQueries вызывает инвалидация сразу всех квери', async () => {
```suggestion
  it('invalidateQueries вызывает инвалидацию сразу всех квери', async () => {
```

2023-09-14 10:22 UTC, sk-iv approved these changes

2023-09-15 11:30 UTC, AndTem requested changes

2023-09-15 11:30 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +    [...this.cacheableStores.entries()].forEach((entrie) => {
Зачем нужен spread?

2023-09-15 11:30 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +      const store = entrie[1];
Сделай деструктуризацию

2023-09-15 11:30 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +   * @description метод для инвалидации сразу всех квери разом
```suggestion
   * @description метод инвалидации всех query
```

2023-09-15 11:30 UTC, AndTem commented on README.md
> +Может возникнуть необходимость инвалидации вообще всех имеющихся quiery. Для этого предназначен отдельный метод `invalidateQueries`
Лишняя литератруность в доке.
"Для инвалидации всех query необходимо использовать метод..."

2023-09-18 05:55 UTC, Ofigelov commented on package/src/MobxQuery/MobxQuery.ts
> +    [...this.cacheableStores.entries()].forEach((entrie) => {
для преобразования Map в массив, и последующего перебора каждого элемента

2023-09-18 05:56 UTC, Ofigelov commented on package/src/MobxQuery/MobxQuery.ts
> +      const store = entrie[1];
при деструктуризации получаем первым элементом имя, которое нигде не используется, и линтер активно сигнализирует об этом, и не дает закоммитить

2023-09-18 05:57 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +      const store = entrie[1];
@Ofigelov [,store]

2023-09-18 09:06 UTC, AndTem approved these changes

2023-09-18 09:11 UTC, merged