feat(UIKIT-772,MobxQuery): Основной функционал
kaluga-astral/mobx-query pull request #2
Opened 2023-06-08 13:38 UTC by Ofigelov

# Чеклист

- [ - ] Написать тесты - в следующем пул реквесте
- [ + ] Описать jsdoc
- [ - ] Обновить документацию в README.md - в следующем пулреквесте

2023-06-09 06:00 UTC, AndTem commented on package/src/CacheableQuery/CacheableQuery.ts
> +  public get isSuccess() {
jsdoc

2023-06-09 06:01 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> + * @variation 'network-only' - для каждого обращения будет создаваться новый квери,
Опять коммент про реализацию, а не про использование.
Должно быть написано: 'network-only' - данные всегда беруться из сети, при этом ответ записывается в кэш

2023-06-09 06:01 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +export enum CachePolicy {
```suggestion
export enum FetchPolicy {
```

2023-06-09 06:04 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +export enum CachePolicy {
Это должен быть union, а не enum.
Enum вечно импортировать придется, а строку указать проще

2023-06-09 06:05 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +type CacheKey = string | string[] | number | { [key: string]: CacheKey };
Это должно экспортироваться из пакета

2023-06-09 06:06 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> + * @description фабрика создающая сторы данных, и запускающая их инвалидацию по указанным ключам
Сервис, позволяющий кэшировать данные.
В jsdoc надо писать текст для пользователя, а не для разработчика пакета

2023-06-09 06:06 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> + * @description фабрика создающая сторы данных, и запускающая их инвалидацию по указанным ключам
Сервис, позволяющий кэшировать данные.
В jsdoc надо писать текст для пользователя, а не для разработчика пакета

2023-06-09 06:07 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +  private readonly defaultOnError?: OnError;
```suggestion
  private readonly defaultErrorHandler?: OnError;
```

2023-06-09 06:08 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +   * @description приватный метод, который занимается проверкой наличия стора по ключу,
Опять бесполезная часть коммента. И так видно, что метод приватный

2023-06-09 06:08 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +    key: unknown[],
У тебя же описан тип для ключей

2023-06-09 06:10 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +    if (type === CachedStoreTypes.cacheable) {
Вместо этого if и лишней переменной можно просто разнести создание разных кэшей по разным функциям

2023-06-09 06:11 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +    return this.getCachedQuery(
Если сделать два отдельных метода, вместо одного, то приводить типы не придется и принцип единственной ответственности нарушаться не будет

2023-06-09 06:13 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +      .map((key: KeyHash) => {
Сейчас сложность алгоритма n в квадрате.
Если заюзаешь reduce, то будет просто n

2023-06-09 06:13 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +    touchedKeys.forEach((key) => {
Лишние проходы. Это можно делать сразу в reduce

2023-06-09 06:21 UTC, Ofigelov commented on package/src/AuxiliaryQuery/AuxiliaryQuery.ts
> +  public getSingleTonePromise = (executor: Executor<TResult>) => {
суть в том, что могут одновременно вызваться sync и async методы, из разных мест, для одного и того же стора, и вот чтобы избежать двух запросов к бэку, они сводятся к одному промису

2023-06-09 06:25 UTC, Ofigelov commented on package/src/MobxQuery/MobxQuery.ts
> +    return this.getCachedQuery(
сделать два метода которые будут делать одно и то же, просто с разными типами?

2023-06-09 06:26 UTC, AndTem commented on package/src/AuxiliaryQuery/AuxiliaryQuery.ts
> +  public getSingleTonePromise = (executor: Executor<TResult>) => {
Понял, название не подходящее. Это не синглтон

2023-06-09 06:59 UTC, AndTem requested changes

2023-06-09 06:59 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +export type InfinityExecutor<TResult> = (
Где-то infinity, а где-то infnite

2023-06-09 06:59 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +    if (this.isInvalid || !(this.isLoading || Boolean(this.internalData))) {
Надо вторую часть || вынести в константу для лучшего понимания кода

2023-06-09 06:59 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +      (this.enabledAutoFetch &&
Вынести в отдельную константу для лучшего понимания кода

2023-06-09 06:59 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +    runInAction(() => {
Кажется, что runInAction здесь лишний

2023-06-09 06:59 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +      // и если колличество элементов в ответе меньше,
Логика некорректна. Последний запрос может содержать items === count и логика сломается.
isEndReached должен расчитываться на основе totalCount, полученного с бэкенда при запросе данных

2023-06-09 06:59 UTC, AndTem commented on package/src/MutationQuery/MutationQuery.ts
> + * @description простой стор для отправки данных,
Store для произведения операции над данными

2023-06-09 07:00 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +    return this.getCachedQuery(
Ну либо писать перегузку. Лучше два разных

2023-06-09 07:09 UTC, Ofigelov commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +    runInAction(() => {
весь метод вызывается внутри then, и я так понимаю, что все реактивные данные внутри должны меняться только внутри runInAction

2023-06-09 07:10 UTC, Ofigelov commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +      // и если колличество элементов в ответе меньше,
у нас на бэкенде нету totalCount, это принципиальная позиция нашего архитектора.

2023-06-09 07:12 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +      // и если колличество элементов в ответе меньше,
Это проблема вашего продукта.
Данная логика неверна

2023-06-09 07:12 UTC, Ofigelov commented on package/src/MutationQuery/MutationQuery.ts
> + * @description простой стор для отправки данных,
может сойдемся на - "простой стор, подойдет для запросов, которые не требуют кэширования,
пример - POST запросы" ?

2023-06-09 07:14 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +    runInAction(() => {
Получается, что handleSuccess знает о том, что он выполняется внутри промиса, а он этого знать не должен.
Попробуй убрать runinAction, мне кажется, что должно работать (сет стора происходит здесь в контексте одного стора, mobx должен разрулить)

2023-06-09 07:26 UTC, Ofigelov commented on package/src/types.ts
> +export type Sync<TResult, TError, TExecutorParams = void> = (
Там же ниже есть QueryBaseActions, используется как implements для классов

2023-06-09 07:28 UTC, AndTem commented on package/src/types.ts
> +export type Sync<TResult, TError, TExecutorParams = void> = (
Но при этом руками методы приводятся к типу Sync. Зачем?

2023-06-09 07:38 UTC, Ofigelov commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +      // и если колличество элементов в ответе меньше,
я бы сказал что ни одна реализация не является оконечно верной. 
Конкретно нам нужна именно эта, и она работает как надо. Если мы вынесем это наружу, то выглядит так, что у нас же не выйдет использовать этот пакет в продукте.

2023-06-09 08:09 UTC, Ofigelov commented on package/src/types.ts
> +export type Sync<TResult, TError, TExecutorParams = void> = (
дженерики

2023-06-09 08:11 UTC, Ofigelov commented on package/src/MobxQuery/MobxQuery.ts
> +    return this.getCachedQuery(
я немного переделал, запушил изменение отдельным коммитом, посмотри плиз. Вроде должно всем подойти.

2023-06-09 08:19 UTC, Ofigelov commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +      // и если колличество элементов в ответе меньше,
и еще я считаю, что завязываться на `totalCount` не стоит, потому что мы тогда будем требовать определнный формат ответа, и никак иначе. В нашей реализации, мы только лишь ожидаем что ответ это какой то массив.
Единственная проблема, которую мы получим с этим, это один лишний запрос в крайнем кейсе, когда последняя отданная страница содержит ровно то колличество, сколько может содержать страница, а следующая уже просто пустая, сверх лимита от того, что есть у бэкенда. Кейс редкий, и думаю что бэк не должен от такого умереть.

2023-06-12 17:11 UTC, Ofigelov commented on package/src/MobxQuery/MobxQuery.ts
> +      .map((key: KeyHash) => {
сколько не раздумывал, не увидел варианта как сделать сильно дешевле. Но все таки немного снизил, и даже удалось отказаться зависимости в виде lodash. Посмотри плиз.

2023-06-13 07:04 UTC, sk-iv commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +   * @description колличество запрашиваемых элементов
```suggestion
   * @description количество запрашиваемых элементов
```

2023-06-13 07:13 UTC, sk-iv commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +  public increment = () => {
на усмотрение, но кажется что по названию непонятно, что делает метод, обычно этот метод называется `fetchMore`

2023-06-13 08:10 UTC, sk-iv commented on package/src/Query/Query.ts
> +  private internalData: TResult | undefined;
возможно тут также надо написать @description

2023-06-13 08:20 UTC, Ofigelov commented on package/src/Query/Query.ts
> +  private internalData: TResult | undefined;
он был, андрей отметил его как бесполезный )

2023-06-13 08:22 UTC, AndTem commented on package/src/Query/Query.ts
> +  private internalData: TResult | undefined;
Так надо написать полезный

2023-06-13 10:20 UTC, Ofigelov commented on package/src/Query/Query.ts
> +  private internalData: TResult | undefined;
добавил

2023-06-13 10:33 UTC, sk-iv approved these changes

2023-06-14 06:28 UTC, AndTem requested changes

2023-06-14 06:28 UTC, AndTem commented on package/src/Query/Query.ts
> +      !Boolean(this.internalData) &&
Похоже, что три этих флага можно заменить на один isSuccess

2023-06-14 06:28 UTC, AndTem commented on package/src/AuxiliaryQuery/AuxiliaryQuery.ts
> +   * @description метод для объединения synс и async логики в одну,
Запутанный комментарий. Мне кажется, что это метод, который устраняет гонку запросов

2023-06-14 09:02 UTC, Ofigelov commented on package/src/Query/Query.ts
> +      !Boolean(this.internalData) &&
только тогда наверное два, проверка на загрузку все таки нужна

2023-06-14 09:13 UTC, AndTem approved these changes

2023-06-14 09:13 UTC, merged