test(UIKIT-1081): Обновлены тесты в соответствии с новыми требованиями
kaluga-astral/mobx-query pull request #25
Opened 2023-12-11 08:55 UTC by Ofigelov

# Чеклист

- [x] Написать тесты
- [ ] Описать jsdoc
- [ ] Обновить документацию в README.md

2023-12-11 09:03 UTC, AndTem requested changes

2023-12-11 09:03 UTC, AndTem commented on package/src/Query/Query.test.ts
> +    it('При успешном запросе устанавливаются соответствующие флаги', async () => {
У тебя здесь идет сначала условие, потом результат, потом предмет тестирования. Должно быть наоборот.

2023-12-11 09:03 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  describe('обработка ошибок', () => {
Группировать либо по предету можгнго. либюо по услвие.
Это ни то, ни другое.
В твоем случае здесь кажется должно быть: При провальном запросе

2023-12-11 09:03 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  describe('enabledAutoFetch tests', () => {
https://industrious-search-cdf.notion.site/Astral-Frontend-Unit-Testing-Guide-71120289ed89424e912ebe7fa8b7e39b#0bcf9ccc088a4f6dbf24bdd974250ec0

2023-12-11 09:03 UTC, AndTem commented on package/src/Query/Query.test.ts
> +    it('при фейле запроса, повторные обращения к data не происходит повторных запросов', async () => {
Порядок формата не в правильной последовательности

2023-12-14 14:06 UTC, AndTem requested changes

2023-12-14 14:06 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.test.ts
> +  describe('Инвалидация для сложносоставного ключа', async () => {
Это ни предмет, ни условие

2023-12-14 14:06 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.test.ts
> +    it('Запрос не начался, если ключ не верный', async () => {
Вообще не понятно что значит не верный ключ

2023-12-14 14:06 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.test.ts
> +    it('Запрос не начался, если ключ не верный', async () => {
![image](https://github.com/kaluga-astral/mobx-query/assets/23665108/95800ce9-50df-4327-8ee6-8009818b8004)

2023-12-14 14:06 UTC, AndTem commented on package/src/Query/Query.test.ts
> +    it('Соответствующие флаги устанавливаются', async () => {
Больше конкретики:
Статусные флаги принимают изначальное состояние

2023-12-14 14:06 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  describe('Синхронизация данных через dataStorage', () => {
Сложно понять о чем речь. Это ни предмет, ни условие

2023-12-14 14:06 UTC, AndTem commented on package/src/Query/Query.test.ts
> +    it('Квери B получает данные, запрошенные в сторе A', async () => {
Тест кейс не должен быть завязан на реализации теста

2023-12-14 14:06 UTC, AndTem commented on package/src/Query/Query.test.ts
> +      await query.async();
надо разделить тест на успешный и фейл кейсы

2023-12-18 04:23 UTC, Ofigelov commented on package/src/Query/Query.test.ts
> +  describe('Синхронизация данных через dataStorage', () => {
Я не знаю что тут еще писать. Тут проверяется механизм синхронизации данных. По моему иначе и не напишешь.

2023-12-18 04:24 UTC, Ofigelov commented on package/src/Query/Query.test.ts
> +    it('Квери B получает данные, запрошенные в сторе A', async () => {
я пытался уменьшить количестве expect. тогда верну обратно.

2023-12-18 04:30 UTC, Ofigelov commented on package/src/Query/Query.test.ts
> +      await query.async();
мне кажется, что по отдельности они не будут нести смысла, т.к. неважно какая политика у квери, результаты одиночных запросов будут идентичны. Проще тогда удалить его полностью.

2023-12-18 06:14 UTC, AndTem approved these changes

2023-12-18 08:12 UTC, lordniken approved these changes

2023-12-18 08:13 UTC, merged