chore: Переезд хранилища данных в отдельную сущность
kaluga-astral/mobx-query pull request #3
Opened 2023-06-15 06:24 UTC by Ofigelov

# Чеклист

- [ - ] Написать тесты - следующим пул реквестом
- [ + ] Описать jsdoc
- [ + ] Обновить документацию в README.md - следующим пул реквестом

2023-06-15 06:29 UTC, AndTem commented
не chore, а refactor.
Загугли как пользоваться чекбоксами в markdown

2023-06-15 10:48 UTC, AndTem requested changes

2023-06-15 10:48 UTC, AndTem commented on package/src/Query/Query.ts
> +      !(this.isLoading || this.isSuccess)
нужен коммент и вынос в отдельную переменную

2023-06-15 10:48 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +    const fetchPolicy = params?.fetchPolicy || this.defaultFetchPolicy || '';
зачем здесь пустая строка? Это лишнее

2023-06-15 10:48 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteDataStorage/InfiniteDataStorage.ts
> +export class InfiniteDataStorage<TData extends unknown[]>
я думаю, что не имеет смысла делать два DataStorage. Можно сделать один, а логику increment просто вынести в InfiniteQuery

2023-06-15 10:48 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +      [...key, fetchPolicy],
Для чего в key добавляется fetchPolicy? Для network-only получается, что в хранилище по ключу записывается store, который должен умереть после выполнения, но он не умрет из-за того, что доступен по ссылке в map хранилища

2023-06-15 10:48 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +          ) as InfiniteDataStorage<TResult[]>,
Костыльное приведение типов. getCachedQery вообще по сути все равно какие там данные лежат

2023-06-15 10:49 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteDataStorage/InfiniteDataStorage.ts
> +export class InfiniteDataStorage<TData extends unknown[]>
Также сериализация данных на сервере для ssr может в таком решение принести сложности из-за того, что данные раскинуты

2023-06-15 10:55 UTC, Ofigelov commented on package/src/MobxQuery/MobxQuery.ts
> +      [...key, fetchPolicy],
я решил добавить fetchPolicy в ключ, чтобы сторы `network-only` были бы отделены от `cache-first`. 
Если мы не будем хранить ссылки на `network-only`, тогда у нас единомоменто может существовать сколь угодно много `network-only`  сторов одного ключа. Точно ли это то, что нам нужно?

2023-06-15 10:58 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +      [...key, fetchPolicy],
Да, этого мы добиться и хотим.
Нам надо, чтобы каждый стор network-only ничего не знал о другом таком же

2023-06-16 07:36 UTC, AndTem requested changes

2023-06-16 07:36 UTC, AndTem commented on package/src/Query/Query.ts
> +      // если политика 'network-only',
бесполезные комментарии. По названию переменных и так понятно все

2023-06-16 07:36 UTC, AndTem commented on package/src/Query/Query.ts
> +      !(this.isLoading || this.isSuccess);
Я имел в виду вынести в отдельную переменную именно эту часть условия

2023-06-16 07:36 UTC, AndTem commented on package/src/DataStorage/DataStorage.ts
> + * @description хранилище данных простого Query
описание некорректное

2023-06-16 07:36 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.ts
> +   * @description хранилище данных, для обеспечения синхронизации данных между 'network-only' и 'cache-first' инстансами
Это просто хранилище данных. network-only это побочные фичи

2023-06-16 07:53 UTC, AndTem approved these changes

2023-06-16 07:57 UTC, merged