feat(UIKIT-1493): Реализация фонового изменения данных
kaluga-astral/mobx-query pull request #31
Opened 2024-06-30 11:22 UTC by Ofigelov

Избавился от `description` префиксов в js-doc
Перенос флага инвалидации в Auxiliary
Переезд основных статусов в хранилище статусов
Переезд computed статусов из каждого query в родительский класс, для уменьшения бойлерплейт кода
Добавлена фабрика хранилищ статусов
Добавлена логика фоновых статусов

# Чеклист

- [x] Написать тесты
- [x] Описать jsdoc
- [x] Обновить документацию в README.md

2024-07-01 11:10 UTC, AndTem requested changes

2024-07-01 11:10 UTC, AndTem commented on package/src/Query/Query.ts
> +  extends QueryContainer<TError, AuxiliaryQuery<TResult, TError>, TIsBackground>
Наследование для сторов не работает ведь. + в консоли ошибка должна быть
Уверен, что тут все ок?

2024-07-01 11:10 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  describe('При использовании при использовании backgroundStatusStorage', () => {
ДУБЛИРОВАНИ
```suggestion
  describe('При использовании backgroundStatusStorage', () => {
```

2024-07-01 11:10 UTC, AndTem commented on package/src/QueryContainer/QueryContainer.ts
> +    private readonly backgroundStatusStorage: StatusStorage<TError> | null,
Из-за того, что он может быть null я вижу заморочки в коде.
Может просто required param?

2024-07-01 11:10 UTC, AndTem commented on package/src/QueryContainer/QueryContainer.ts
> +  public get background(): TIsBackground extends true
Разве не backgroundStatus должно быть?

2024-07-01 11:10 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.ts
> +  createQuery = <
```suggestion
  public createQuery = <
```

2024-07-01 11:10 UTC, AndTem commented on package/src/Mutation/Mutation.test.ts
> +  it('background равен null', () => {
```suggestion
  it('Background равен null', () => {
```

2024-07-01 11:10 UTC, AndTem commented on package/src/Mutation/Mutation.test.ts
> +  it('background равен null', () => {
https://kaluga-astral.github.io/style-guide/docs/rules/tests/naming#%D1%82%D0%B5%D1%81%D1%82-%D0%BA%D0%B5%D0%B9%D1%81-%D0%B4%D0%BE%D0%BB%D0%B6%D0%B5%D0%BD-%D0%BD%D0%B0%D1%87%D0%B8%D0%BD%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D1%81-%D0%B1%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B9-%D0%B1%D1%83%D0%BA%D0%B2%D1%8B

2024-07-01 11:10 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  describe('При использовании при использовании backgroundStatusStorage', () => {
Имеет ли смысл дублировать тесты для background, если сам код для него написан в QueryContainer?

2024-07-01 11:10 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  describe('При использовании при использовании backgroundStatusStorage', () => {
Тоже самое касается всех тестов на статусные флаги

2024-07-01 12:34 UTC, Ofigelov commented on package/src/AuxiliaryQuery/AuxiliaryQuery.ts
> +  private checkBackgroundAndSet = (setStorage: SetStorage<TError>) => {
Я сначала попробовал так сделать, и понял, что в каждом методе проверяю одно и то же, 1 в 1, и выглядит это не очень. Кмк сейчас публичные методы выполняют вполне говорящие действие, проверка и запуск соответствующего действия относительно статуса.

2024-07-01 12:37 UTC, Ofigelov commented on package/src/Query/Query.ts
> +  extends QueryContainer<TError, AuxiliaryQuery<TResult, TError>, TIsBackground>
Да, я нашел вариант, что наследование работает, если мы используем `makeObserverable` и не `makeAutoObserverable`. Пока что везде, где бы я не пробовал, заводится успешно.

2024-07-01 12:57 UTC, Ofigelov commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  describe('При использовании при использовании backgroundStatusStorage', () => {
Сам по себе QueryContainer не имеет логики, просто транслирует флаги из хранилищ. А вот в вариациях квери уже реализация. И при этом в Mutation в принципе нет фонового режима. Там уже не совпадающий набор тестов.

2024-07-01 13:00 UTC, Ofigelov commented on package/src/QueryContainer/QueryContainer.ts
> +  public get background(): TIsBackground extends true
это же было не точно?) я думаю что постфикс Status излишний, и при этом не в полной точности не описывает что там находится. Считаю, что в основном будет использоваться вид `query.background.isLoading`, и в такой записи вполне очевидно что используется

2024-07-01 13:12 UTC, Ofigelov commented on README.md
> +await query.async();
Немного переместил строчки, теперь должно быть норм

2024-07-01 13:12 UTC, Ofigelov commented on README.md
> +## Режим фонового обновления
добавил

2024-07-02 07:49 UTC, AndTem approved these changes

2024-07-02 07:49 UTC, AndTem commented on package/src/StorageFactory/StorageFactory.test.ts
> +  it('Метод getStorage создает стор при попытке получить данные', () => {
```suggestion
  it('GetStorage создает стор при попытке получить данные', () => {
```

2024-07-02 07:49 UTC, AndTem commented on package/src/StorageFactory/StorageFactory.test.ts
> +  it('Метод getStorage создает стор при попытке получить данные', () => {
"Метод" можно опустить

2024-07-02 08:51 UTC, merged