feat(UIKIT-772,MobxQuery): Добавил тесты
kaluga-astral/mobx-query pull request #4
Opened 2023-06-16 08:05 UTC by Ofigelov

# Чеклист

- [ ] Написать тесты
- [ ] Описать jsdoc
- [ ] Обновить документацию в README.md - в следующем коммите

2023-06-16 08:16 UTC, AndTem requested changes

2023-06-16 08:16 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  it('Проверяем инит состояние, пока ничего не запросили', () => {
Неверная формулировка тест кейса.
Тест кейс должен описывать что умеет делать сервис. Тесты - это ведь еще и документация
Пример здесь: Устанавливаются дефолтные флаги статусов

2023-06-16 08:16 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  it('Проверяем положительный кейс', async () => {
При успешном запросе все необходимые флаги меняются

2023-06-16 08:16 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  it('Проверяем работу флагов успешности и ошибки, меняющемся поведении', async () => {
При последовательных запросах меняется state статусов

2023-06-16 08:16 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.test.ts
> +describe('MobxQuery tests', () => {
tests - лишнее

2023-06-16 08:16 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  it('Проверяем "network-only" политику c sync', async () => {
Читай [style guide](https://track.astral.ru/soft/wiki/pages/viewpage.action?pageId=3772645403#id-%D0%A2%D0%B5%D1%81%D1%82%D1%8B-%D0%92describe%D1%83%D0%BA%D0%B0%D0%B7%D1%8B%D0%B2%D0%B0%D0%B5%D1%82%D1%81%D1%8F%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B0%D0%B8%D0%BB%D0%B8%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%B0,%D0%B4%D0%BB%D1%8F%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D0%BE%D0%B3%D0%BE%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D1%83%D1%8E%D1%82%D1%81%D1%8F%D1%82%D0%B5%D1%81%D1%82-%D0%BA%D0%B5%D0%B9%D1%81%D1%8B).
должно быть что-то вроде Query.sync:fetchPolicy=network-only: при вызове данные берутся из сети

2023-06-16 08:16 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  it('Проверяем fetchMore', async () => {
Я уже оставлял комментарии по названиям.
Еще имей в виду, что один тест должен проверять что-то одно. Твой тест кажется проверяет все что только можно

2023-06-16 08:16 UTC, AndTem commented on package/src/DataStorage/DataStorage.test.ts
> +    console.log(storageA, storageB);
log

2023-06-16 08:23 UTC, Ofigelov commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  it('Проверяем fetchMore', async () => {
конкретно в этой ситуации, проверяю кейс использования метода, используя его, меняются статусы и данные. Не представляю как можно его разбить на части, и чтобы это было достаточно понятно.
Давай я просто каждому `expect` буду добавлять второй аргумент комментарий, который будет показываться, если эта проверка не прошла?

2023-06-16 08:25 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  it('Проверяем fetchMore', async () => {
Нет, это не решение.
Ты в этом тесте должен проверить только то, что относится непосредственно к fetchMore. Проверка статусов и тп уже есть в других тестах, здесь это проверять не имеет смысла

2023-06-16 08:28 UTC, Ofigelov commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  it('Проверяем fetchMore', async () => {
чем плохо, то что тут проверяются статусы? 
например я ожидаю, что при вызове fetchMore должен включаться флаг isLoading. Разве это неправильно?

2023-06-16 09:04 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  it('Проверяем fetchMore', async () => {
У тебя другой тест уже это проверяет.
К чему эти лишние проверки?

2023-06-16 09:11 UTC, Ofigelov commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  it('Проверяем fetchMore', async () => {
Это сложно отслеживать, какие тесты, что досконально проверяют. Слишком строгое правило. Типа если один флаг где-то проверил, то снова где-то проверять нельзя. 
К примеру, спустя месяц, мы расширяем функционал, который использует части того, что уже было сделано, и разработано, и теперь стоит задача - написать тесты. Мне идти, и сканировать все все написанные тесты, чтобы понять какой флаг где уже проверятся, чтобы не дай бог не написать какую нибудь простую проверку еще раз?
Сомневаюсь что тесты надо писать именно с таким прицелом. Выглядит как бессмысленная экономия на спичках.

2023-06-16 09:32 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  it('Проверяем fetchMore', async () => {
https://vc.ru/dev/115923-atomarnost-v-testirovanii-dlya-novichkov

2023-06-16 09:36 UTC, AndTem commented on package/src/InfiniteQuery/InfiniteQuery.test.ts
> +  it('Проверяем fetchMore', async () => {
На счет данного теста я был не прав. У тебя тут проверяется только то, что относится к fetchMore.
Все верно

2023-06-19 06:22 UTC, sk-iv commented on package/src/MobxQuery/MobxQuery.test.ts
> +      'queryAsc дергаем дату у всех сторов, что бы тригернуть загрузку',
тут и у двух ожиданий ниже
```suggestion
      'queryAsc дергаем дату у всех сторов, чтобы тригернуть загрузку',
```

2023-06-19 06:31 UTC, sk-iv commented on package/src/Query/Query.test.ts
> +      'при фейле запроса, флаг успешности должен переключится в true',
```suggestion
      'при фейле запроса, флаг успешности должен переключится в false',
```

2023-06-19 06:36 UTC, sk-iv commented on package/src/Query/Query.test.ts
> +  it('Проверяем отрицательный кейс вызова syc, когда передан обработчик ошибки по умолчанию', async () => {
```suggestion
  it('Проверяем отрицательный кейс вызова sync, когда передан обработчик ошибки по умолчанию', async () => {
```

2023-06-19 12:21 UTC, AndTem requested changes

2023-06-19 12:21 UTC, AndTem commented on package/src/DataStorage/DataStorage.test.ts
> +  it('DataStorageFactory Проверяем создание инстансов хранилищ', () => {
DataStorageFactory - это другой класс. Дня него свой describe должен быть

2023-06-19 12:21 UTC, AndTem commented on package/src/MobxQuery/MobxQuery.test.ts
> +  it('Cоздание сторов', async () => {
Здесь текста не изменил

2023-06-19 12:21 UTC, AndTem commented on package/src/MutationQuery/MutationQuery.test.ts
> +  it('Проверяем положительный кейс c sync', async () => {
Здесь текста не изменил

2023-06-19 12:21 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  it('isSuccess+isError - success', async () => {
Не понятно чем речь

2023-06-19 12:21 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  it('invalidate+sync:fetchPolicy=cache-first: Проверяем инвалидацию запуском sync', async () => {
Опять "Проверяем"

2023-06-19 12:23 UTC, AndTem commented on package/src/Query/Query.test.ts
> +  it('invalidate+sync:fetchPolicy=cache-first: Проверяем инвалидацию запуском sync', async () => {
Где-то плюс, где-то двоеточие.
Сделай везде двоеточие для однообразности.
Повнимательнее, много всяких мелких незначительных опечаток

2023-06-21 06:57 UTC, AndTem approved these changes

2023-06-21 06:58 UTC, merged