feat(UIKIT-772,MobQuery): Документация
kaluga-astral/mobx-query pull request #5
Opened 2023-06-20 04:06 UTC by Ofigelov

# Чеклист

- [ ] Написать тесты
- [ ] Описать jsdoc
- [ ] Обновить документацию в README.md

2023-06-21 07:09 UTC, AndTem requested changes

2023-06-21 07:09 UTC, AndTem commented on README.md
> +- executor - исполнитель запроса. Хэндлер, который будет совершать запрос данных. Второй аргумент при создании query
Хендлер - это обработчик. executor - это не обработчик

2023-06-21 07:09 UTC, AndTem commented on README.md
> +# Basic usage
Здесь должен быть полный пример с инициализацией и выполнением запроса.
Думаю, что идеально отобразить пример, как у нас в продукте (немного упрощенный только) с: инициализацией, подпиской в store на query, отображение в компоненте флагов

2023-06-21 07:09 UTC, AndTem commented on README.md
> +## 3. Синхронный полуавтомат.
ручной и полуавтомат вообще ничем не отличаются.
В первом случае есть просто onError, onSuccess.
Считаю, что это лишний раздел

2023-06-21 07:09 UTC, AndTem commented on README.md
> +Для корректной работы инвалидации, при создании query требуется использование `ключа`, c помощью которого и происходит вся магия.
Про магию вообще лишнее

2023-06-21 07:09 UTC, AndTem commented on README.md
> +# Несколько вариантов использования
Похоже, что здесь заголовок должен быть - query

2023-06-21 07:09 UTC, AndTem commented on README.md
> +Для удобства, мы создали специальный `query`, который содержит дополнительный метод `fetchMore` и при вызове оного, происходит запрос с увеличенными счетчиками. Данные ответа на этот запрос, будут ск
Считаю, что здесь есть лишние ссылки на то, как это реализовано внутри. Дока должна описывать просто то, что умеет пакет

2023-06-21 07:09 UTC, AndTem commented on README.md
> +В `executor` будет передан объект с `offset` - количество элементов отступа от начала списка, и `count` - количество элементов на одну страницу.
Часто встречается текстовое описание типов ts. Почему бы тогда просто не дать сигнатуру в ts?

2023-06-21 07:09 UTC, AndTem commented on README.md
> +// ждем фоновой загрузки
when для ожидания может добавить?

2023-06-21 07:09 UTC, AndTem commented on README.md
> +Для этого предназначен дополнительный вид query, который никак не кешируется.
Это не доп, вид query. Это отдельная сущность

2023-06-21 08:44 UTC, Ofigelov commented on README.md
> +# Basic usage
мне кажется, это будет слишком сложный пример, пользователь запутается в том, что для чего нужно, и что мы вообще хотели этим показать. 
Сойдемся на примере, который будет показывать разницу между этими политиками?

2023-06-21 08:47 UTC, Ofigelov commented on README.md
> +Для удобства, мы создали специальный `query`, который содержит дополнительный метод `fetchMore` и при вызове оного, происходит запрос с увеличенными счетчиками. Данные ответа на этот запрос, будут ск
ну может про isEndReached и далее лишнее, но остальное я бы оставил.

2023-06-21 08:52 UTC, AndTem commented on README.md
> +# Basic usage
политики здесь ни при чем.
Этот пример должен показывать как использование пакета выглядит в реальном коде.
А для политик, кстати, да, должен быть отдельный пример

2023-06-21 08:53 UTC, AndTem commented on README.md
> +Для удобства, мы создали специальный `query`, который содержит дополнительный метод `fetchMore` и при вызове оного, происходит запрос с увеличенными счетчиками. Данные ответа на этот запрос, будут ск
Лишние детали просто опусти

2023-06-21 08:55 UTC, Ofigelov commented on README.md
> +# Basic usage
Может пример реального кода тогда оставим для песочницы? Пусть тут в доке будут простые примеры.

2023-06-21 08:57 UTC, AndTem commented on README.md
> +# Basic usage
Ну можно и так. Только в примере должна быть не одна инициализация, но и вызов + подписка на состояния

2023-06-23 05:42 UTC, AndTem commented
feat -> doc

2023-07-05 07:59 UTC, closed without merging